# Generated by Django 5.2.10 on 2026-01-27 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_verified_users_activated_users_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='phone',
        ),
    ]
